-
  hosts: all
  any_errors_fatal: true
  tasks:
  - shell: apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*
    args:
      warn: False
  - command: "swapoff /dev/sda5"
  - command: dd if=/dev/zero of=/dev/sda5 bs=64k
    ignore_errors: yes
  - copy:
      src: fdisk
      dest: /fdisk
  - shell: |
      sed -e 's/\t\([\+0-9a-zA-Z]*\)[ \t].*/\1/' < /fdisk | fdisk /dev/sda || true; rm /fdisk
    args:
      warn: false
  - lineinfile:
      regexp: swap
      dest: /etc/fstab
      state: absent
